### ISSUE TITLE
CfdpTXCmd not working

### ISSUE THREAD

**Issue by DavidEdell** [traclabs/cfe_ros2_bridge_plugin#9]
The CFE CFDP TX Command has been defined in cfe_plugin_config.yaml, but has deliberately been omitted from the "commands" array for now.

When this field is added to the "commands" array, the bridges fail to run.

**Comment by ana-GT** [comment]
### Summary of issue:

We have a ROS2 message **CFTxFileCmd**, which corresponds to the C structure **CF_TxFileCmd** defined in the cf app. When we tried to add this message in the juicer_util/config/cfe_plugin_config.yaml , the bridges were crashing.

The reason for this was a typo when filling the **structure** field in the .yaml file:

```
        CfdpTXCmd:
          structure: CFTxFileCmd
          cfe_mid: '0x18b3'
          cmd_code: 2
          topic_name: cfdp_tx_cmd
```
The structure field must contain the name of the ROS2 message (no the C structure in cFS). In this case, this field had to have the name **CFTxFileCmd**, opposed to CF_TXFileCmd (C struct name). Fixing this and adding this item in the command section works now.

This issue was addressed in PR 10: https://github.com/traclabs/cfe_ros2_bridge_plugin/pull/10
